In [ ]:
import torch
# Construct a tensor c of shape (3,2) filled with all zeros
# Then set element (0,1) to 10, and element (1,0) to 100  
c = torch.tensor([[0,0],[0,0],[0,0]])
print('c is a tensor:', torch.is_tensor(c))
print('Correct shape: ', c.shape == (3,2))
print('All zeros: ', (c == 0).all().item()== 1)
c[0,1] = 10
c[1,0] = 100
print('\nAfter mutating: ')
print('Correct shape: ', c.shape == (3,2))
print('c[0,1] correct: ', c[0,1] == 10)
print('c[1,0] correct: ', c[1,0] == 100)
print('Rest of c is still zero: ', (c==0).sum().item() == 4)

# Use a tensor creation function to create a tensor shape of (2,3,4) filled entirely with 7
print()
e = torch.full((2,3,4), 7)
print('e is a tensor:', torch.is_tensor(e))
print('e has correct shape: ', e.shape == (2,3,4))
print('e is filled with sevens: ', (e==7).all().item() == 1)

# Create a 64-bit floating-point tensor of shape (6,) filled with evenly-spaced values between 10 and 20
# linspace : creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
print()
x = None
x = torch.linspace(10,20, steps=6, dtype=torch.float64)
print('x is a tensor: ', torch.is_tensor(x))
print('x has correct shape: ', x.shape == (6,))
print('x has correct dtype: ', x.dtype == torch.float64)
y = [10, 12, 14, 16, 18, 20]
correct_vals = all(a.item() == b for a, b in zip(x, y))
print('x has correct valus: ', correct_vals)

#Your turn: practice indexing tensors with slices
# We will use this helper function to check your results
def check(orig, actual, expected):
  expected = torch.tensor(expected)
  same_elements = (actual == expected).all().item() == 1
  same_storage = (orig.storage().data_ptr() == actual.storage().data_ptr())
  return same_elements and same_storage
# Create the following rank 2 tensor of shape (3, 5)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]]
print()
a = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
b, c2, d, e2 = None, None, None, None

# Extract the last row of a, and store it in b; it should have rank 1.
b = a[2,:]  #sau a[-1,:]
print(b)
print('rank b:' ,b.dim())
print('b correct:', check(a, b, [11, 12, 13, 14, 15]))

# Extract the third col of a, and store it in c; it should have rank 2.
print()
c2 = a[:,2:3] # am pus c2 deoarece am volosit c mai sus
print(c2)
print('rank c2: ', c2.dim())
print('c2 correct:', check(a, c2, [[3], [8], [13]]))

# Use slicing to extract the first two rows and first three columns
print()
d = a[:2, :3]
print(d)
print('d correct:', check(a, d, [[1, 2, 3], [6, 7, 8]]))

# Use slicing to extract a subtensor of a consisting of rows 0 
# and 2 and columns 1 and 4. 
print()
e2 = a[0:3:2, 1:5:3]
print(e2)
print('e correct:', check(a, e2, [[2, 5], [12, 15]]))

#  Use slicing to modify the tensor x so it has the following contents: #
#     [[1, 0, 2, 2, 2, 2],                                                   
#      [0, 1, 2, 2, 2, 2],                                                   
#      [3, 4, 3, 4, 5, 5],                                                   
#      [3, 4, 3, 4, 5, 5]]                                                   
# This can be achieved using five slicing assignment operations.  
print()
x2 = torch.zeros(4, 6, dtype=torch.int64)     # 4 linii si 6 coloane
print(x2) 
x2[0,0] = 1
x2[1,1] = 1
x2[:2, 2:] = 2
x2[2:, 0:3:2] = 3
x2[2:, 1:4:2] = 4
x2[2:, 4:] = 5
print(x2)
expected = [
    [1, 0, 2, 2, 2, 2],
    [0, 1, 2, 2, 2, 2],
    [3, 4, 3, 4, 5, 5],
    [3, 4, 3, 4, 5, 5],
]
print('correct:', x2.tolist() == expected)

# Use integer array indexing to create a tensor of shape (4, 4) where: 
# - The first two columns are the same as the first column of a              
# - The next column is the same as the third column of a                     
# - The last column is the same as the second column of a                    
# Store the resulting tensor in b.

print()
a3 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('Here is a:')
print(a3)
b3, c3, d3 = None, None, None

idx = [0, 0, 2, 1]
b3 = a3[:, idx]
print('\nHere is b:')
print(b3)
expected = [[1, 1, 3, 2], [4, 4, 6, 5], [7, 7, 9, 8], [10, 10, 12, 11]]
print('b correct:', b3.tolist() == expected)

# Use integer array indexing to create a new tensor which is the same  
# as a, but has its rows reversed. Store the result in c. 

print()
idx1 = torch.tensor([3, 2, 1, 0])
c3 = a3[idx1]  # pun fara : cand am pe randuri reverse
print('\nHere is c:')
print(c3)
expected = [[10, 11, 12], [7, 8, 9], [4, 5, 6], [1, 2, 3]]
print('c correct:', c3.tolist() == expected)

# Use integer array indexing to create a new tensor by selecting one   
# element from each column of a:                                             
# - From the first column, take the second element.                          
# - From the second column, take the first element.                          
# - From the third column, take the fourth element.                          
# Store the result in d.  

print()
rows = torch.tensor([1, 0, 3]) # secod, first, fourth element
columns = torch.tensor([0, 1, 2]) # first, second, third column 
d3 = a3[rows, columns]
print('\nHere is d:')
print(d3)
expected = [4, 2, 12]
print('d correct:', d3.tolist() == expected)

# Use boolean masks to count the number of negative elements in x.
print()
def num_negative(x):
  """
  Return the number of negative values in the tensor x
 
  Inputs:
  - x: A tensor of any shape
 
  Returns:
  - num_neg: Number of negative values in x
  """
  num_neg = 0

  mask = (x < 0)
  num_neg = torch.sum(mask).item()
  return num_neg



# Make a few test cases
torch.manual_seed(598)
x0 = torch.tensor([[-1, -1, 0], [0, 1, 2], [3, 4, 5]])
x1 = torch.tensor([0, 1, 2, 3])
x2 = torch.randn(100, 100)
assert num_negative(x0) == 2
assert num_negative(x1) == 0
assert num_negative(x2) == 4984
print('num_negative seems to be correct!')

print()
def make_one_hot(x):
  """
  Construct a tensor of one-hot-vectors from a list of Python integers.

  Input:
  - x: A list of N ints

  Returns:
  - y: A tensor of shape (N, C) where C = 1 + max(x) is one more than the max
       value in x. The nth row of y is a one-hot-vector representation of x[n];
       In other words, if x[n] = c then y[n, c] = 1; all other elements of y are
       zeros.
  """

  c4 = 1 + max(x)
  t = torch.tensor(x)
  y = torch.nn.functional.one_hot(t, c4)

  return y


def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x3 = [1, 4, 3, 2]
y0 = make_one_hot(x3)
print('Here is y0:')
print(y0)
assert check_one_hot(x3, y0), 'y0 is wrong'

x4 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x4)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x4, y1), 'y1 is wrong'

print('all checks pass!')
print()

#  Use reshape operations to create x7 from x5   

x5 = torch.arange(24)
print('Here is x5:')
print(x5)

x6 = x5.view(2, 3, 4)  # a * b * c = 24
print('x6 :', x6)

x7 = x6.permute(1, 0, 2)
x8 = x7.reshape(3, 8)

print(x7)
print(x8)

expected = [
    [0, 1,  2,  3, 12, 13, 14, 15],
    [4, 5,  6,  7, 16, 17, 18, 19],
    [8, 9, 10, 11, 20, 21, 22, 23]]
print('Correct:', x8.tolist() == expected)

print()
#def zero_row_min(x):
  
 # y = x.clone()

  # Complete the implementation of this function.                        
  

 # return y
#TODO: This code

# torch.dot - are input 2 tensori unidimensionali ( vectori)
#           - are output produsul scalar a celor 2 vectori
#           - echivalent cu a.dot(b)
# torch.mm - matrix-matrix product
# torch.mv - computes matrix-vector products
# torch.bmm - batched versions of torch.mm and torch.addmm 
# (computes matrix-matrix and matrix-vector multiplications plus a bias)

B, N, M, P = 3, 2, 5, 4
x10 = torch.rand(B, N, M)  # Random tensor of shape (B, N, M)
y10 = torch.rand(B, M, P)  # Random tensor of shape (B, M, P)

# We can use a for loop to (inefficiently) compute a batch of matrix multiply
# operations
z1 = torch.empty(B, N, P)  # Empty tensor of shape (B, N, P)
for i in range(B):
  z1[i] = x10[i].mm(y10[i])
print('Here is the result of batched matrix multiply with a loop:')
print(z1)

z2 = x10.bmm(y10)
print(z2)
##############################################################################
# TODO: Use bmm to compute a batched matrix multiply between x and y; store  #
# the result in z2.                                                          #
##############################################################################
# Replace "pass" statement with your code
pass
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is the result of batched matrix multiply with bmm:')
print(z2)

# The two may not return exactly the same result; different linear algebra
# routines often return slightly different results due to the fact that
# floating-point math is non-exact and non-associative.
diff = (z1 - z2).abs().max().item()
print('\nDifference:', diff)
print('Difference within threshold:', diff < 1e-6)

print()
# TODO: GPU

 




  


c is a tensor: True
Correct shape:  True
All zeros:  True

After mutating: 
Correct shape:  True
c[0,1] correct:  tensor(True)
c[1,0] correct:  tensor(True)
Rest of c is still zero:  True

e is a tensor: True
e has correct shape:  True
e is filled with sevens:  True

x is a tensor:  True
x has correct shape:  True
x has correct dtype:  True
x has correct valus:  True

tensor([11, 12, 13, 14, 15])
rank b: 1
b correct: True

tensor([[ 3],
        [ 8],
        [13]])
rank c2:  2
c2 correct: True

tensor([[1, 2, 3],
        [6, 7, 8]])
d correct: True

tensor([[ 2,  5],
        [12, 15]])
e correct: True

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])
tensor([[1, 0, 2, 2, 2, 2],
        [0, 1, 2, 2, 2, 2],
        [3, 4, 3, 4, 5, 5],
        [3, 4, 3, 4, 5, 5]])
correct: True

Here is a:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Here is b:
tensor([[ 1,  1,  3,  2],
        [ 4